---
title: Кампания детски градини и ясли 2019
output:
  word_document: default
  pdf_document: default
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE, message=FALSE,comment=NA,cache=F, cache.lazy=FALSE, fig.width = c(8), fig.height = c(5))

requiredPackages = c('knitr','tidyr','dplyr','ggplot2')
for(p in requiredPackages){
  if(!require(p,character.only = TRUE)) install.packages(p)
  library(p,character.only = TRUE)
}
setwd("C:/Documents/GitHub/Kindergarten-Scraping/kindergartens")
Sys.setlocale("LC_CTYPE", "bulgarian")

path_to_report = "waiting.csv"
```


```{r}
FullList <- read.csv("waiting.csv",stringsAsFactors = F)
FullList$tail[FullList$tail=="Социални"]="Общи"


Places <- read.csv("places.csv",stringsAsFactors = F)
Places$tail[Places$tail=="Социални"]="Общи"

Places <- Places %>% group_by(born, kg, region, tail) %>% summarise(places = sum(places))

Applications <- FullList %>% 
  filter (preference == "3т. / (1-во желание)") %>% 
  group_by(born, kg,region, tail) %>% 
  summarise(applications = n_distinct(id))

Fill <- merge(Places, Applications, by = c("born", "kg", "region", "tail"), all.x = T)
Fill$applications[is.na(Fill$applications)]<-0


```

```{r}

```


```{r}
region <-Fill %>% filter (tail == "Общи" & born == 2017) %>% 
  group_by(region) %>% 
  summarise(index = round(sum(applications)/sum(places),1), sum(places)) %>% 
  arrange( desc(index))

region$region <- factor(region$region, levels = region[order(region$index),]$region)


```

```{r}
ggplot(region, aes(x=region, y =index,fill = index )) +
  geom_bar(stat="identity") + 
  scale_fill_gradient2(low="dark green", mid = "yellow" ,
                       high="dark red",midpoint = 2, name = "")+
  #scale_y_continuous(limits = c(0,8)) +
  coord_flip()+
  geom_text(aes(label=index), size =2.3,hjust=-0.25)+
  scale_x_discrete(name="")+
  scale_y_continuous(name="Брой деца за едно място")
```
```{r}

```


